### ISSUE TITLE
How/where would CaaS and FaaS fit into the list?

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#5]
In the beginning of Section 1.7, you talk about 3 models of cloud based computing.  You could also include Containers as a Service (CaaS) and Function as a Service to this list.

CaaS - example RedHat OpenShift (recently rebranded as CaaS)
FaaS - AWS Lambda, serverless FaaS

Not sure what impact mentioning these would have to Figure 1.4 or the callout in grey right before section 1.9

**Comment by carnellj** [comment]
Hi Josh,

Good callout.  I have added a call out right before chapter 1.8 that briefly talks about FaaS and CaaS.  I do not want to spend a lot of time on the subject because they are really alternative infrastructure approaches  and could be there own books.  However, they do deserve some mention.

You should see the new text in  when I complete chapter 1.
